api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Controllers/Note.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Controllers/Observer.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Controllers/Statistici.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Queries/MiniStatisticsQueryHandler.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Queries/ObserverRequestsHandler.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Startup.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/ViewModels/MiniStatisticsRequests.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/ViewModels/ResetDeviceIdRequest.cs
=> added ministatistics

api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Controllers/Raspunsuri.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Queries/RaspunsuriQueryHandler.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/ViewModels/FiltruRaspunsuriModel.cs, api/MonitorizareVot.Ong/src/MonitorizareVot.Api/ViewModels/RaspunsModel.cs
#110 #109 #108
Filter by `County`, `PollingStationNumber`, `ObserverId`
=> #110 #109 #108 Filter by `County`, `PollingStationNumber`, `ObserverId`

api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Queries/RaspunsuriQueryHandler.cs
=> fix table aliases

api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Queries/RaspunsuriQueryHandler.cs
hate for inlinesql - this has got to go
#108 #109 #110
=> finally fixed query

api/MonitorizareVot.Ong/src/MonitorizareVot.Api/Properties/launchSettings.json, api/MonitorizareVot.Ong/src/MonitorizareVot.Domain.Ong/Models/VoteMonitorContextExtensions.cs
Updated the launching URL for Swagger and fixed two generation queries so that the domain can be generated without errors.
=> Update Swagger UI launch url; fix domain generation

frontend/package-lock.json, frontend/proxy.conf.json, frontend/src/app/app.component.html, frontend/src/app/components/answer/answer.component.html, frontend/src/app/components/answer/answer.component.ts, frontend/src/app/components/header/header.component.html, frontend/src/app/components/header/header.component.scss, frontend/src/app/models/answer.filters.model.ts, frontend/src/app/models/answer.thread.model.ts, frontend/src/app/routing/guards/load-answer-list.guard.ts, frontend/src/app/store/answer/answer.actions.ts, frontend/src/app/store/answer/answer.effects.ts, frontend/src/app/store/answer/answer.reducer.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/ro.json
Closes #108 #109 #110
Obviously copy text needs to change. Needs styling.
Happy to finish if I have direction on this
=> Add filtering for answerResults

frontend/src/app/store/answer/answer.effects.ts
=> fix answears query params 

frontend/src/app/components/answer/answer.component.html
=> redesign search form

frontend/README.md, frontend/angular-cli.json, frontend/package.json, frontend/proxy.conf.json, frontend/src/app/components/header/header.component.ts, frontend/src/app/components/login/login.component.ts, frontend/src/app/services/answers.service.ts, frontend/src/app/store/answer/answer.effects.ts, frontend/src/app/store/form/form.effects.ts, frontend/src/app/store/note/note.effects.ts, frontend/src/app/store/statistics/statistics.effects.ts, frontend/src/environments/environment.prod.ts, frontend/src/environments/environment.qa.ts, frontend/src/environments/environment.ts, frontend/src/typings.d.ts
I try to fix #149 but i found out that in this way API blocks our calls due to CORS.
@RaduCStefanescu maybe we should disable CORS for API .
=> use environments

frontend/src/app/store/note/note.actions.ts, frontend/src/app/store/note/note.effects.ts, frontend/src/app/store/note/note.reducer.ts
=> fix note loading by renaming params

frontend/src/app/components/observers/observers.component.html, frontend/src/app/components/observers/observers.component.ts, frontend/src/app/store/observers/observers.actions.ts, frontend/src/app/store/observers/observers.effects.ts, frontend/src/app/store/observers/observers.reducer.ts, frontend/src/app/store/observers/observers.state.ts, frontend/src/app/store/store.module.ts
=> display total number of observers

frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/app/components/components.module.ts, frontend/src/app/components/header/header.component.html, frontend/src/app/components/notifications/notifications.component.html, frontend/src/app/components/notifications/notifications.component.scss, frontend/src/app/components/notifications/notifications.component.ts, frontend/src/app/components/notifications/observer-tile/observer-tile.component.html, frontend/src/app/components/notifications/observer-tile/observer-tile.component.scss, frontend/src/app/components/notifications/observer-tile/observer-tile.component.ts, frontend/src/app/core/apiService/api.service.ts, frontend/src/app/models/notification.model.ts, frontend/src/app/routing/app.routes.ts, frontend/src/app/services/notifications.service.ts, frontend/src/assets/i18n/en.json
Implement #159 
All credits goes to @RaulDr
still missing some validations , maybe some bugs.
I didn't knew how to populate NotificationModel  so it is random strings for channel and sender.
=> implement minimum functionality for sending notifications

frontend/src/app/app.module.ts, frontend/src/app/components/observers/observer-profile/observer-profile.component.html, frontend/src/app/components/observers/observer-profile/observer-profile.component.ts, frontend/src/app/components/observers/observers-card/observers-card.component.html, frontend/src/app/components/observers/observers-card/observers-card.component.scss, frontend/src/app/components/observers/observers-card/observers-card.component.ts, frontend/src/app/components/observers/observers.component.ts, frontend/src/app/models/api-list-response.model.ts, frontend/src/app/services/observers.service.ts, frontend/src/assets/i18n/en.json
=> implement reset password to a given password

frontend/src/app/components/notifications/notifications.component.html, frontend/src/app/components/notifications/notifications.component.scss, frontend/src/app/components/notifications/observer-tile/observer-tile.component.html, frontend/src/app/components/notifications/observer-tile/observer-tile.component.scss
try to fix/ redesign #183.
I redesigned  tiles and they look like in screenshot right now. 
Hopefully you will like this.
=> redesign checkbox tile for observers

frontend/src/app/components/answer/answer-details/answer-details.component.ts, frontend/src/app/models/note.model.ts
=> fix notes for answears

frontend/src/app/components/answer/answer.component.html, frontend/src/app/components/answer/answer.component.scss, frontend/src/app/components/answer/answer.component.ts
Implement functionality for #186
=> implement reset functionality

frontend/src/app/components/answer/answer.component.ts, frontend/src/app/services/answers.service.ts
Closes  #248 
Tested locally with the production API. File is downloaded correctly and the content of the file is as expected.
=> Fix file download for download answers

frontend/src/app/components/notifications/notifications.component.ts
Closes #252  
Ran the Angular app against API locally.  API url now correctly uses to/from polling number like this - https://localhost:5001/api/v1/observer/active?countyCodes=AR&fromPollingStationNumber=1&toPollingStationNumber=3&currentlyCheckedIn=true
=> setting to and from variables correctly

frontend/src/app/components/answer/answer.component.html, frontend/src/app/components/answer/answer.component.ts
Closes https://github.com/code4romania/monitorizare-vot-ong/issues/257
See loader in button on the screenshots.
Go to answers page and click Download button. Test if download success and failed.
=> Add loader for download answers action https://github.com/code4romania/monitorizare-vot-ong/issues/257

src/app/components/forms/option/option.component.html, src/app/shared/icon-toggle-input/icon-toggle-input.component.html, src/app/shared/icon-toggle-input/icon-toggle-input.component.ts, src/app/shared/shared.module.ts, src/assets/i18n/en.json, src/assets/i18n/ro.json, src/styles.scss
Signed-off-by: Ajinkya Jeurkar <ajinkyajeurkar@gmail.com>
Closes #267 
- Tested locally
Demo -
Screenshots -
=> Issue #267 - Added tooltip for option icons.

package.json, src/app/components/header/header.component.html, src/app/components/header/header.component.ts, src/app/core/token/token.service.ts, src/assets/i18n/en.json, src/assets/i18n/ro.json
Closes #277  
Added [auth0/angular-jwt](https://www.npmjs.com/package/@auth0/angular-jwt) package to help with decoding the jwt token
Used the sub (subject) property of decoded token to get username
Tested by running the application locally, screen shots below
=> adding logout functionality

src/app/components/header/header.component.html, src/app/components/header/header.component.scss, src/app/components/header/header.component.ts
=> fix(header): make hambuger menu work on smaller screens

src/app/components/forms/form-create/form-create.component.html, src/app/components/forms/form-create/form-create.component.scss, src/app/components/forms/forms.component.scss, src/app/components/forms/option/option.component.html, src/app/components/forms/option/option.component.scss, src/app/components/forms/question/question.component.html, src/app/components/forms/question/question.component.scss, src/app/components/forms/section/section.component.html, src/app/components/forms/section/section.component.scss
Fixed padding and responsive design on the forms page
Closes #279
Tested by using the browser device toolbar and testing with iPad and iPad pro layout. (lg to md for bootstrap).
mobile
=> updated form spacing and mobile

src/app/components/login/login.component.ts
Closes #XXX 
Bumped authentication API to version 2 which now supports registering FCM Token from observers apps. 
For the Admin's app shouldn't be any change rather than the endpoint.
Tested that the login works as expected and the user is authenticated with correct credentials.
This shouldn't be merged until https://github.com/code4romania/monitorizare-vot/pull/322 will be ready and merged.
=> Updated authentication API to V2

src/app/components/observers/observer-profile/observer-profile.component.ts, src/app/components/observers/observers.component.ts, src/assets/i18n/en.json, src/assets/i18n/ro.json
Closes #293
Implements the logic behind the Delete button in the observer list item dropdown.
Uses 'DELETE ​/api​/v1​/observer' endpoint.
Tested manually using local environment configs.
=> Implemented DELETE /api/v1/observer endpoint in observers list.

src/app/components/statistics/statistics-card/statistics-card.component.html
Header and subheader are now on one line
Closes #294
=> 1 line on cards
